name: CI Pipeline
# Configura servidor de CI para executar o pipeline de tarefas abaixo (jobs) quando 
# um push ou pull request for realizado tendo como alvo a branch main
on:
  push:
    branches:
      - main
      - develop
      - feature/**
      - release/**
      - hotfix/**
  pull_request:
    branches:
      - main
jobs:
  tests:
    runs-on: ubuntu-latest # Os comandos serão executados em um sistema operacional Linux
    steps:
    - name: Checkout
      uses: actions/checkout@v4 # Faz o checkout do código recebido
    - name: Setup Python
      uses: actions/setup-python@v5 # Configura o Python 3.12
      with:
        python-version: "3.12"
    - name: Install dependencies # Instala as dependências do código
      run: |
        pip install -r requirements.txt
    - name: Run Tests # Executada os testes de unidade
      run: |
        pytest